#!./virt_env/bin/python
#
import sys
import os
import shutil
import rwt

def log(msg):
    sys.stdout.write(">> " + msg + "\n")

# site/css
# site/images/portraits
shutil.copytree("public", "site")

# site/404.html
log("Creating 404.")
data = {}
data['title'] = '404'
data['type'] = 'post'
data['content'] = open('pages/404.html').read()
rwt.render(data, 'site/404.html')

# site/about.html
log("Creating about.")
data = {}
data['title'] = 'About'
data['type'] = 'post'
data['content'] = open('pages/about/index.html').read()
rwt.render(data, 'site/about.html')

# Load all posts (name, summary, tags, content (markdown))
# yaml + markdown
posts = rwt.load_posts()
log("Loaded %s interviews." % len(posts))

# site/interviews/NAME/index.html (individual interviews)
for p in posts:
    name = p.yaml['name']
    dot_name = name.replace(" ", ".")
    log("interview: %s" % name)
    data = p.yaml  # name, person, summary, categories
    data['dot_name'] = dot_name
    data['title'] = "Interview with: " + name
    data['markdown'] = p.html()
    data['time'] = 'XXXXXXXXXXXXXXXXX'
    out_file = 'site/interviews/%s/index.html' % dot_name
    rwt.render(data, out_file, 'interview.html')


# site/index.html (landing)
# site/pageXXXX/index.html (pagination)

# TODO
# - default template
#    - last update time
#    - # interviews, # categories , # of bits
#    - licence CSS
#    - expand bits in markkown
# - interview template
#    - fix posted time
# - landing page + pagination





